name: Duplicate Checker
on: 
  pull_request:

jobs:
  cpd:
    runs-on: ubuntu-latest
    name: Check duplicated code
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
      - name: Check duplication
        run: npx jscpd --min-tokens 40 .
