name: Duplicate Checker
on: 
  pull_request:
  push:
  workflow_dispatch: 

jobs:
  cpd:
    runs-on: ubuntu-latest
    name: Check duplicated code
    steps:
      - uses: actions/checkout@v4
      - name: Check duplication
        run: npx jscpd --min-tokens 40 .
